### ISSUE TITLE
simulator black screen when executing from remote machine via ssh

### ISSUE THREAD

**Issue by ypa** [bendyworks/bwoken#20]
I have Xcode 4.6 and iphone simulator 6.0 on the machine. I'm able to run bwoken tests just fine from the machine itslef. But when I run from a remote machine via ssh. The simulator shows up but when the app launches it shows a blank, black colored screen and the tests are not seeing the UI elements and return UIAElementNil.

I needed to be able to run remotely because I was trying to setup the machine as a Jenkins slave so that I can do the builds from the CI interface.

**Comment by listrophy** [comment]
Probably gonna mark this as "won't fix" because of the technicalities involved.

If you can somehow have the ssh'ed shell trigger bwoken from outside itself, that'll probably work.

**Comment by ypa** [comment]
Thanks for a quick response and creating this awesome tool. In case anyone else having the same issue, I have this worked around by running Jenkins slave agent on the slave machine ("Launch slave agents via Java Web Start" on Jenkins slave node setup) instead of launching slave via ssh. Using that setup simulator works fine with bwoken tests.

**Comment by listrophy** [comment]
I'm glad you figured it out! If you write up a blog post, I'd be happy to link to it from the bwoken site.

**Comment by tobi512** [comment]
I'm struggling with the same problem for some time now. This behavior seems to occur, because instruments wants to have login and password on command line. If you use instruments command itself, you'll see this authentication prompt sometimes (sometimes just the gui login).

I'm pretty sure that this prompt appears internally when bwoken executes the instruments command and after a few seconds the tests fail because no valid user/password was entered and instruments cannot control your app.

The solution from @ypa is not an option for us, we have jenkins running on a mac mini and only have ssh access via public authentication!

Anybody else got a solution to pass the command line authentication prompt? Otherwise the whole UIAutomation test stuff is pretty useless for us.
