### ISSUE TITLE
1/3 of all tests randomly fail

### ISSUE THREAD

**Issue by nicolai86** [bendyworks/bwoken#3]
Hey!

First, thanks for this great wrapper for UIAutomation. The setup is really straight forward and it's easy to get going.

I've setup a really simple sample application with two buttons and a small 1.5 second animation at startup - all I test for is to see that both buttons are actually available in the view.

This simple test case fails about 1/3 of all test runs.

See my attached test case:

```
#import "../../../../tuneup/tuneup.js"

test "Initial screen has two buttons", (target, app) ->
  target.delay(2) # wait until animation is over
  window = app.mainWindow()
  assertNotNull window.elements()["buttonA"], "buttonA is missing"
  assertNotNull window.elements()["buttonB"], "buttonB is missing"
```

Any ideas on why that is? 

I've checked for common errors: 
- the accessibilityLabel is set correctly
- the tests fail even if the animation at startup is disabled
- adding / removing delays doesn't change the problem

**Comment by listrophy** [comment]
Hi @leahpar! While I'd like to help you either way, we first need to determine if this is a bwoken issue or a UIAutomation issue.

Please try to take bwoken out of the loop by importing the resulting javascript file (found in integration/tmp/javascript) into UIAutomation.app. You may have to tweak your import path for tune_up.js when you do this.

If you encounter the same problem when running through the GUI app, then it's a UIAutomation problem and not a bwoken one. That's probably good news because then you'll be able to ask a general UIAutomation question, the expert population of which is MUCH bigger. =)

**Comment by nicolai86** [comment]
Hey @listrophy ! Thanks for your fast reply.

I've changed the paths from relative to absolute to work with Instruments - the results indicate that it's actually a UIAutomation problem! Yay for that. 1 out of 6 runs was successful. 

So we can close this issue here. Do you have some suggestions on where I could start to track down the probem?

Thanks for your time & help!

**Comment by listrophy** [comment]
Sorry... I got nothin'. Stack Overflow tends to be pretty good. :(
