### ISSUE TITLE
Xcworkspace vs Xcodeproj

### ISSUE THREAD

**Issue by tobi512** [bendyworks/bwoken#31]
Hey guys, 
first of all thanks for this great tool!

I'm not using a workspace in my project, just have the xcodeproj file. 
In your setup instructions you tell us to create a workspace, but bwoken works just fine without the xcworkspace file.

Can you tell me a little more about this, should i create a workspace anyway?
It would be easier for me to keep going with the xcodeproj file only...

Thanks in advance!

**Comment by listrophy** [comment]
@tobi512 Thanks for taking the time to ask this question. As far as I'm concerned, every iOS project I'm ever going to do in the future is going to use [CocoaPods](https://github.com/CocoaPods/CocoaPods), which requires the use of a workspace instead of just a xcodeproj file. I also believe all iOS developers should be using CocoaPods as well.

As such, I don't have much motivation to support xcodeproj. If you can provide a patch that provides this, I'd be happy to consider it. I would, however, suggest waiting until the next release, since the architecture of passing arguments to bwoken will change significantly.

In the meantime, creating a workspace that simply contains your xcodeproj is quite simple and shouldn't cause you much difficulty... though I don't exactly know your setup. :smiley:

**Comment by tobi512** [comment]
@listrophy Thank for your reply!
I already deleted the workspace file from the project-folder and it's still working fine!
To be honest, i was just curious about any sideeffects that could occur in the future...
